apiVersion: apps/v1
kind: Deployment
metadata:
  name: abn-freesprint-k8s-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abn-freesprint-k8s-lab
  template:
    metadata:
      labels:
        app: abn-freesprint-k8s-lab
    spec:
      containers:
      - name: abn-freesprint-k8s-lab
        image: kbhatia90/abn-freesprint-k8s-lab
        ports:
        - containerPort: 8080
