apiVersion: v1
kind: Pod
metadata:
  name: abn-freesprint-k8s-lab
  labels:
    name: abn-freesprint-k8s-lab
spec:
  containers:
  - name: abn-freesprint-k8s-lab
    image: kbhatia90/abn-freesprint-k8s-lab
    ports:
      - containerPort: 8080
